const TEXT_DURATIONS = [5, 8, 10, 15];
const VIDEO_RESOLUTIONS = ["720P", "1080P"];

export const VIDEO_MODEL_CATEGORIES = [
  { id: "text", label: "文生视频" },
  { id: "image", label: "图生视频" },
  { id: "reference", label: "参考生视频" },
  { id: "edit", label: "编辑 / 动画" },
];

export const VIDEO_MODELS = [
  {
    id: "wan2.7-t2v",
    label: "万相 2.7 文生视频",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "text",
    protocol: "t2v",
    featured: true,
    supportsAudio: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "有声、多镜头、声画同步",
  },
  {
    id: "wan2.7-t2v-2026-06-12",
    label: "万相 2.7 文生视频 06-12",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "text",
    protocol: "t2v",
    supportsAudio: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "固定版本 2026-06-12",
  },
  {
    id: "wan2.7-t2v-2026-04-25",
    label: "万相 2.7 文生视频 04-25",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "text",
    protocol: "t2v",
    supportsAudio: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "固定版本 2026-04-25",
  },
  {
    id: "wan2.6-t2v",
    label: "万相 2.6 文生视频",
    family: "Wan 2.6",
    provider: "dashscope",
    category: "text",
    protocol: "t2vLegacy",
    supportsAudio: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "有声、多镜头叙事",
  },
  {
    id: "wan2.5-t2v-preview",
    label: "万相 2.5 文生视频",
    family: "Wan 2.5",
    provider: "dashscope",
    category: "text",
    protocol: "t2vLegacy",
    supportsAudio: true,
    durations: [5, 10],
    resolutions: ["480P", "720P", "1080P"],
    ratios: true,
    summary: "有声、5 或 10 秒",
  },
  {
    id: "wan2.2-t2v-plus",
    label: "万相 2.2 文生视频 Plus",
    family: "Wan 2.2",
    provider: "dashscope",
    category: "text",
    protocol: "t2vLegacy",
    durations: [5],
    resolutions: ["480P", "1080P"],
    ratios: true,
    summary: "稳定增强、无音频",
  },
  {
    id: "wanx2.1-t2v-turbo",
    label: "万相 2.1 文生视频 Turbo",
    family: "Wan 2.1",
    provider: "dashscope",
    category: "text",
    protocol: "t2vLegacy",
    durations: [5],
    resolutions: ["480P", "720P"],
    ratios: true,
    summary: "快速生成、无音频",
  },
  {
    id: "wanx2.1-t2v-plus",
    label: "万相 2.1 文生视频 Plus",
    family: "Wan 2.1",
    provider: "dashscope",
    category: "text",
    protocol: "t2vLegacy",
    durations: [5],
    resolutions: ["720P"],
    ratios: true,
    summary: "质量增强、无音频",
  },
  {
    id: "happyhorse-1.1-t2v",
    label: "HappyHorse 1.1 文生视频",
    family: "HappyHorse",
    provider: "dashscope",
    category: "text",
    protocol: "t2v",
    durations: [5, 8, 15],
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "24 fps 文生视频",
  },
  {
    id: "wan2.7-i2v",
    label: "万相 2.7 图生视频",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "image",
    protocol: "i2v27",
    featured: true,
    imageMin: 1,
    imageMax: 2,
    supportsAudio: true,
    acceptsVideo: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    summary: "首帧、首尾帧、视频续写",
  },
  {
    id: "wan2.7-i2v-2026-04-25",
    label: "万相 2.7 图生视频 04-25",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "image",
    protocol: "i2v27",
    imageMin: 1,
    imageMax: 2,
    supportsAudio: true,
    acceptsVideo: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    summary: "固定版本 2026-04-25",
  },
  ...[
    ["wan2.6-i2v", "万相 2.6 图生视频", "有声、多镜头"],
    ["wan2.6-i2v-flash", "万相 2.6 图生视频 Flash", "快速生成、可选音频"],
  ].map(([id, label, summary]) => ({
    id,
    label,
    family: "Wan 2.6",
    provider: "dashscope",
    category: "image",
    protocol: "i2vLegacy",
    imageMin: 1,
    imageMax: 1,
    supportsAudio: true,
    durations: TEXT_DURATIONS,
    resolutions: VIDEO_RESOLUTIONS,
    summary,
  })),
  {
    id: "wan2.5-i2v-preview",
    label: "万相 2.5 图生视频",
    family: "Wan 2.5",
    provider: "dashscope",
    category: "image",
    protocol: "i2vLegacy",
    imageMin: 1,
    imageMax: 1,
    supportsAudio: true,
    durations: [5, 10],
    resolutions: ["480P", "720P", "1080P"],
    summary: "有声、首帧驱动",
  },
  ...[
    ["wan2.2-i2v-plus", "万相 2.2 图生视频 Plus", ["480P", "1080P"], "稳定增强"],
    ["wan2.2-i2v-flash", "万相 2.2 图生视频 Flash", ["480P", "720P", "1080P"], "快速生成"],
    ["wanx2.1-i2v-turbo", "万相 2.1 图生视频 Turbo", ["480P", "720P"], "快速生成"],
    ["wanx2.1-i2v-plus", "万相 2.1 图生视频 Plus", ["720P"], "质量增强"],
  ].map(([id, label, resolutions, summary]) => ({
    id,
    label,
    family: id.includes("2.2") ? "Wan 2.2" : "Wan 2.1",
    provider: "dashscope",
    category: "image",
    protocol: "i2vLegacy",
    imageMin: 1,
    imageMax: 1,
    durations: id.includes("turbo") ? [3, 4, 5] : [5],
    resolutions,
    summary: `${summary}、无音频`,
  })),
  {
    id: "wan2.2-kf2v-flash",
    label: "万相 2.2 首尾帧 Flash",
    family: "Wan 2.2",
    provider: "dashscope",
    category: "image",
    protocol: "kf2vLegacy",
    imageMin: 2,
    imageMax: 2,
    durations: [5],
    resolutions: ["480P", "720P", "1080P"],
    summary: "首尾帧过渡",
  },
  {
    id: "wanx2.1-kf2v-plus",
    label: "万相 2.1 首尾帧 Plus",
    family: "Wan 2.1",
    provider: "dashscope",
    category: "image",
    protocol: "kf2vLegacy",
    imageMin: 2,
    imageMax: 2,
    durations: [5],
    resolutions: ["720P"],
    summary: "首尾帧过渡",
  },
  {
    id: "agnes-video-v2.0",
    label: "Agnes Video V2.0",
    family: "Agnes",
    provider: "agnes",
    category: "image",
    protocol: "agnes",
    imageMin: 1,
    imageMax: 5,
    durations: [5, 8, 15],
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "图生视频、关键帧",
  },
  {
    id: "wan2.7-r2v",
    label: "万相 2.7 参考生视频",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "reference",
    protocol: "r2v",
    featured: true,
    imageMin: 1,
    imageMax: 5,
    acceptsVideo: true,
    supportsVoiceReference: true,
    durations: [5, 8, 10],
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "多主体、形象与音色参考",
  },
  {
    id: "wan2.7-r2v-2026-06-12",
    label: "万相 2.7 参考生视频 06-12",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "reference",
    protocol: "r2v",
    imageMin: 1,
    imageMax: 5,
    acceptsVideo: true,
    supportsVoiceReference: true,
    durations: [5, 8, 10],
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "固定版本、多主体参考",
  },
  ...[
    ["wan2.6-r2v", "万相 2.6 参考生视频", "有声、多角色叙事"],
    ["wan2.6-r2v-flash", "万相 2.6 参考生视频 Flash", "快速、多角色"],
  ].map(([id, label, summary]) => ({
    id,
    label,
    family: "Wan 2.6",
    provider: "dashscope",
    category: "reference",
    protocol: "r2vLegacy",
    imageMin: 1,
    imageMax: 5,
    acceptsVideo: true,
    durations: [5, 8, 10],
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary,
  })),
  {
    id: "happyhorse-1.1-r2v",
    label: "HappyHorse 1.1 参考生视频",
    family: "HappyHorse",
    provider: "dashscope",
    category: "reference",
    protocol: "r2v",
    imageMin: 1,
    imageMax: 9,
    durations: [5, 8, 15],
    resolutions: VIDEO_RESOLUTIONS,
    ratios: true,
    summary: "多图参考",
  },
  {
    id: "wan2.7-videoedit",
    label: "万相 2.7 视频编辑",
    family: "Wan 2.7",
    provider: "dashscope",
    category: "edit",
    protocol: "videoEdit",
    imageMin: 0,
    imageMax: 4,
    requiresVideo: true,
    durations: [5, 8, 10],
    resolutions: VIDEO_RESOLUTIONS,
    summary: "指令编辑、参考图替换",
  },
  {
    id: "wan2.2-animate-move",
    label: "万相 2.2 图像动作迁移",
    family: "Wan 2.2",
    provider: "dashscope",
    category: "edit",
    protocol: "animateMove",
    imageMin: 1,
    imageMax: 1,
    requiresVideo: true,
    promptOptional: true,
    durations: [5, 10, 15, 30],
    resolutions: ["720P"],
    summary: "参考视频驱动人物动作",
  },
  {
    id: "wan2.2-animate-mix",
    label: "万相 2.2 视频角色替换",
    family: "Wan 2.2",
    provider: "dashscope",
    category: "edit",
    protocol: "animateMix",
    imageMin: 1,
    imageMax: 1,
    requiresVideo: true,
    promptOptional: true,
    durations: [5, 10, 15, 30],
    resolutions: ["720P"],
    summary: "保留动作与场景替换角色",
  },
];

export function getVideoModel(modelId) {
  return VIDEO_MODELS.find((model) => model.id === modelId);
}
